import {test,expect} from '@playwright/test'
test('station data loads on demand, platform filters and level separation keep the same clock',async({page})=>{
 const errors:string[]=[],requests:string[]=[]
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()))
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/')
 await expect(page.getByRole('button',{name:'Play playback'})).toBeVisible()
 expect(requests.some(r=>r.endsWith('/ostkreuz.json'))).toBe(false)
 await page.getByRole('button',{name:'Ostkreuz',exact:false}).click()
 await expect(page.getByRole('heading',{name:'Ostkreuz',exact:true})).toBeVisible()
 await expect(page.getByRole('img',{name:'Ostkreuz relative platform levels'})).toBeVisible()
 await expect(page.getByTestId('clock')).toHaveText('08:00')
 await page.getByRole('combobox',{name:'Choose platform'}).selectOption({label:'Platform 11'})
 await expect(page.locator('.section-call').first()).toContainText('S41')
 expect(await page.locator('.section-call').allTextContents()).toEqual(expect.arrayContaining([expect.stringContaining('Platform 11')]))
 await page.getByRole('button',{name:'Lifts',exact:true}).click()
 expect(await page.locator('[data-connector-mode="5"]').count()).toBeGreaterThan(0)
 await expect(page.locator('[data-connector-mode]:not([data-connector-mode="5"])')).toHaveCount(0)
 await page.getByRole('slider',{name:'Separate platform levels'}).fill('0')
 await expect(page.getByTestId('clock')).toHaveText('08:00')
 await page.locator('.section-call').nth(1).click()
 const callTime=await page.getByTestId('clock').textContent()
 await page.getByRole('button',{name:'The ring',exact:false}).click()
 await expect(page.locator('canvas')).toBeVisible();await expect(page.getByTestId('clock')).toHaveText(callTime!)
 expect(errors).toEqual([])
})
test('station playback advances and unmounting does not leave a second clock running',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');await page.getByRole('button',{name:'Ostkreuz',exact:false}).click()
 await expect(page.getByRole('combobox',{name:'Choose platform'})).toBeVisible()
 await page.getByRole('combobox',{name:'Playback speed'}).selectOption('60')
 await page.getByRole('button',{name:'Play playback'}).click()
 await expect(page.getByTestId('clock')).not.toHaveText('08:00')
 await page.getByRole('button',{name:'Pause playback'}).click();const time=await page.getByTestId('clock').textContent()
 await page.getByRole('button',{name:'Ring & crossings'}).click();await page.waitForTimeout(300)
 await expect(page.getByTestId('clock')).toHaveText(time!)
})
