import {test,expect} from '@playwright/test'
test('closer station inspection preserves time and distinguishes platform dimensions from scene height',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/')
 await page.getByRole('button',{name:'Ostkreuz',exact:false}).click()
 await expect(page.getByTestId('platform-facts')).toContainText('Select a platform')
 await page.getByRole('combobox',{name:'Choose platform'}).selectOption({label:'Platform 11'})
 await expect(page.getByTestId('platform-facts')).toContainText('155 m net built length')
 await expect(page.getByTestId('platform-facts')).toContainText('96 cm above rail')
 await page.getByRole('button',{name:'Zoom into station'}).click()
 await page.getByRole('button',{name:'Zoom into station'}).click()
 await expect(page.getByTestId('station-camera')).toHaveAttribute('transform',/scale\(2\)/)
 await expect(page.getByTestId('clock')).toHaveText('08:00')
 await page.getByRole('combobox',{name:'Choose platform'}).selectOption({label:'Platform 3'})
 await expect(page.getByTestId('platform-facts')).toContainText('152 m net built length')
 await page.getByRole('slider',{name:'Separate platform levels'}).fill('0')
 await expect(page.getByTestId('platform-facts')).toContainText('96 cm above rail')
 await page.getByRole('button',{name:'Reset station view'}).click()
 await expect(page.getByTestId('station-camera')).toHaveAttribute('transform',/scale\(1\)/)
 await expect(page.getByTestId('clock')).toHaveText('08:00')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})
test('station data loads on demand, platform filters and level separation keep the same clock',async({page})=>{
 const errors:string[]=[],requests:string[]=[]
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()))
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/')
 await expect(page.getByRole('button',{name:'Play playback'})).toBeVisible()
 expect(requests.some(r=>r.endsWith('/ostkreuz.json'))).toBe(false)
 await page.getByRole('button',{name:'Ostkreuz',exact:false}).click()
 await expect(page.getByRole('heading',{name:'Ostkreuz',exact:true})).toBeVisible()
 await expect(page.getByRole('img',{name:'Ostkreuz relative platform levels'})).toBeVisible()
 await expect(page.getByTestId('official-bridge-outline')).toBeVisible()
 await page.getByRole('checkbox',{name:'Official bridge outline',exact:true}).uncheck()
 await expect(page.getByTestId('official-bridge-outline')).toHaveCount(0)
 await page.getByRole('checkbox',{name:'Official bridge outline',exact:true}).check()
 await expect(page.getByTestId('official-bridge-outline')).toHaveAttribute('data-source-id','c07_ax_bauwerkimverkehrsbereich_f.DEBEATKB10000iKp')
 await expect(page.getByTestId('clock')).toHaveText('08:00')
 await page.getByRole('combobox',{name:'Choose platform'}).selectOption({label:'Platform 11'})
 await expect(page.locator('.section-call').first()).toContainText('S41')
 expect(await page.locator('.section-call').allTextContents()).toEqual(expect.arrayContaining([expect.stringContaining('Platform 11')]))
 await page.getByRole('button',{name:'Lifts',exact:true}).click()
 expect(await page.locator('[data-connector-mode="5"]').count()).toBeGreaterThan(0)
 await expect(page.locator('[data-connector-mode]:not([data-connector-mode="5"])')).toHaveCount(0)
 await page.getByRole('slider',{name:'Separate platform levels'}).fill('0')
 await expect(page.getByTestId('clock')).toHaveText('08:00')
 await page.locator('.section-call').nth(1).click()
 const callTime=await page.getByTestId('clock').textContent()
 await page.getByRole('button',{name:'The ring',exact:false}).click()
 await expect(page.locator('canvas')).toBeVisible();await expect(page.getByTestId('clock')).toHaveText(callTime!)
 expect(errors).toEqual([])
})
test('station stays usable when the optional official bridge source is unavailable',async({page})=>{
 await page.route('**/ostkreuz-bridge.json',route=>route.fulfill({status:503,body:'Unavailable'}))
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/')
 await page.getByRole('button',{name:'Ostkreuz',exact:false}).click()
 await expect(page.getByRole('checkbox',{name:'Official bridge outline · unavailable'})).toBeDisabled()
 await expect(page.getByTestId('official-bridge-outline')).toHaveCount(0)
 await page.getByRole('combobox',{name:'Choose platform'}).selectOption({label:'Platform 11'})
 await expect(page.locator('.section-call').first()).toContainText('S41')
 await expect(page.getByTestId('clock')).toHaveText('08:00')
})
test('station playback advances and unmounting does not leave a second clock running',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');await page.getByRole('button',{name:'Ostkreuz',exact:false}).click()
 await expect(page.getByRole('combobox',{name:'Choose platform'})).toBeVisible()
 await page.getByRole('combobox',{name:'Playback speed'}).selectOption('60')
 await page.getByRole('button',{name:'Play playback'}).click()
 await expect(page.getByTestId('clock')).not.toHaveText('08:00')
 await page.getByRole('button',{name:'Pause playback'}).click();const time=await page.getByTestId('clock').textContent()
 await page.getByRole('button',{name:'Ring & crossings'}).click();await page.waitForTimeout(300)
 await expect(page.getByTestId('clock')).toHaveText(time!)
})
