import { test, expect } from '@playwright/test'
test('real morning renders, clock pauses and scrubs, crossing and diagram controls preserve time',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/')
 await expect(page.getByRole('heading',{name:'Umlauf'})).toBeVisible()
 await expect(page.locator('canvas')).toBeVisible()
 await expect(page.getByTestId('s41-count')).not.toHaveText('0')
 await page.getByRole('button',{name:'Pause playback'}).click()
 const before=await page.getByTestId('clock').textContent()
 await page.waitForTimeout(250)
 expect(await page.getByTestId('clock').textContent()).toBe(before)
 await page.getByRole('slider',{name:'Study time',exact:true}).fill('27000')
 await expect(page.getByTestId('clock')).toHaveText('07:30')
 await page.getByRole('button',{name:'Ring & crossings'}).click()
 await expect(page.getByRole('button',{name:'Ring & crossings'})).toHaveAttribute('aria-pressed','true')
 await page.getByRole('slider',{name:'Geography to circulation'}).fill('1')
 await expect(page.getByTestId('clock')).toHaveText('07:30')
 await expect(page.getByText('An authored diagram: the Ring becomes a circle.')).toBeAttached()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:`test-results/${test.info().project.name}-crossings.png`,fullPage:true})
 expect(errors).toEqual([])
})
test('source panel explains schedule evidence and returns keyboard focus',async({page})=>{
 await page.goto('/');const trigger=page.getByRole('button',{name:'About the data'})
 await trigger.click();await expect(page.getByRole('heading',{name:'A dated morning.'})).toBeVisible()
 await expect(page.getByRole('link',{name:'CC BY 4.0'})).toBeVisible()
 await page.keyboard.press('Escape');await expect(trigger).toBeFocused()
 await expect(page.getByRole('heading',{name:'A dated morning.'})).not.toBeVisible()
})
test('reduced motion opens paused',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/')
 await expect(page.getByRole('button',{name:'Play playback'})).toBeVisible()
})
